# Generated by Django 3.1.3 on 2020-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discourse_App', '0005_auto_20201104_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
