# Generated by Django 3.1.3 on 2020-11-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discourse_App', '0006_auto_20201104_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
    ]
